'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/components/AuthProvider';
import { createClient } from '@/lib/supabase';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card';
import { ArrowLeft, FileText, Download, Save } from 'lucide-react';
import Link from 'next/link';
import { useToast } from '@/components/ToastProvider';
import jsPDF from 'jspdf';

export default function NewInvoicePage() {
    const { user } = useAuth();
    const router = useRouter();
    const { showToast } = useToast();
    const [loading, setLoading] = useState(false);
    const [clients, setClients] = useState<any[]>([]);

    const [formData, setFormData] = useState({
        clientId: '',
        amount: '',
        dueDate: '',
        description: ''
    });

    useEffect(() => {
        async function fetchClients() {
            if (!user) return;
            const supabase = createClient();
            const { data } = await supabase
                .from('clients')
                .select('id, name')
                .eq('user_id', user.id)
                .order('name');
            if (data) setClients(data);
        }
        fetchClients();
    }, [user]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        setFormData(prev => ({ ...prev, [e.target.name]: e.target.value }));
    };

    const generatePdf = (invoiceNumber: string) => {
        const client = clients.find(c => c.id === formData.clientId);
        const clientName = client ? client.name : 'Unknown Client';

        const pdf = new jsPDF('p', 'mm', 'a4');
        const margin = 20;

        // Header
        pdf.setFont("times", "bold");
        pdf.setFontSize(28);
        pdf.setTextColor(15, 23, 42);
        pdf.text("InvoiceIQ - Financial Intelligence", margin, margin + 10);

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10);
        pdf.setTextColor(100);
        pdf.text("Professional Financial Intelligence", margin, margin + 18);

        // Invoice Details
        pdf.setFontSize(20);
        pdf.setTextColor(0);
        pdf.text("INVOICE", margin, margin + 40);

        pdf.setFontSize(12);
        pdf.text(`Invoice Number: ${invoiceNumber}`, margin, margin + 50);
        pdf.text(`Date Issued: ${new Date().toLocaleDateString()}`, margin, margin + 58);
        pdf.text(`Due Date: ${new Date(formData.dueDate).toLocaleDateString()}`, margin, margin + 66);

        // Billed To
        pdf.setFont("helvetica", "bold");
        pdf.text("Billed To:", margin, margin + 86);
        pdf.setFont("helvetica", "normal");
        pdf.text(clientName, margin, margin + 94);

        // Line Items Table Header
        const tableTop = margin + 114;
        pdf.setFillColor(241, 245, 249); // slate-100
        pdf.rect(margin, tableTop, 170, 10, 'F');
        pdf.setFont("helvetica", "bold");
        pdf.text("Description", margin + 5, tableTop + 7);
        pdf.text("Amount", margin + 140, tableTop + 7);

        // Line Items Content
        pdf.setFont("helvetica", "normal");

        // Handle long descriptions by splitting them
        const splitDescription = pdf.splitTextToSize(formData.description || 'Professional Services rendered', 120);
        pdf.text(splitDescription, margin + 5, tableTop + 20);

        const amountFormatted = Intl.NumberFormat('en-PK', { style: 'currency', currency: 'PKR' }).format(Number(formData.amount));
        pdf.text(amountFormatted, margin + 140, tableTop + 20);

        // Total
        const totalTop = tableTop + 30 + (splitDescription.length * 5);
        pdf.setDrawColor(200);
        pdf.line(margin + 100, totalTop, margin + 170, totalTop);
        pdf.setFont("helvetica", "bold");
        pdf.text("Total Due:", margin + 100, totalTop + 8);
        pdf.text(amountFormatted, margin + 140, totalTop + 8);

        // Footer
        const pdfHeight = pdf.internal.pageSize.getHeight();
        const pdfWidth = pdf.internal.pageSize.getWidth();
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(9);
        pdf.setTextColor(150);

        const footerText = 'Generated by InvoiceIQ — https://iq-invoice.vercel.app/';
        const textWidth = pdf.getStringUnitWidth(footerText) * 9 / pdf.internal.scaleFactor;
        pdf.text(footerText, (pdfWidth - textWidth) / 2, pdfHeight - 15);

        pdf.save(`Invoice_${invoiceNumber}.pdf`);
    };

    const handleSubmit = async (e: React.FormEvent, shouldDownload: boolean) => {
        e.preventDefault();
        if (!user) return;

        if (!formData.clientId || !formData.amount || !formData.dueDate) {
            showToast("Please fill in all required fields.", "error");
            return;
        }

        setLoading(true);
        const supabase = createClient();

        // Generate pseudo invoice number
        const randomStr = Math.random().toString(36).substring(2, 6).toUpperCase();
        const invoiceNumber = `INV-${new Date().getFullYear()}${String(new Date().getMonth() + 1).padStart(2, '0')}-${randomStr}`;

        try {
            const { error: insertError } = await supabase
                .from('invoices')
                .insert({
                    user_id: user.id,
                    client_id: formData.clientId,
                    amount: parseFloat(formData.amount),
                    due_date: formData.dueDate,
                    description: formData.description,
                    status: 'Pending',
                    issue_date: new Date().toISOString().split('T')[0],
                    invoice_number: invoiceNumber
                });

            if (insertError) throw insertError;

            showToast('Success! Invoice created.', 'success');

            if (shouldDownload) {
                generatePdf(invoiceNumber);
            }

            router.push('/dashboard/invoices');
            router.refresh();
        } catch (err: any) {
            console.error("Error creating invoice:", err);
            showToast(err.message || 'Failed to create invoice.', 'error');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="space-y-6 max-w-3xl mx-auto">
            <div className="flex items-center gap-4">
                <Link href="/dashboard/invoices" className="text-muted-foreground hover:text-white transition-colors">
                    <ArrowLeft className="w-5 h-5" />
                </Link>
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Create Invoice</h1>
                    <p className="text-muted-foreground">Generate a new professional invoice and download the PDF.</p>
                </div>
            </div>

            <Card className="border-indigo-500/20 shadow-[0_0_40px_-10px_rgba(99,102,241,0.1)] bg-slate-900/50 backdrop-blur-xl">
                <CardHeader>
                    <CardTitle>Invoice Details</CardTitle>
                    <CardDescription>Fill out the primary billing information below.</CardDescription>
                </CardHeader>
                <CardContent>
                    <form className="space-y-6">
                        <div className="space-y-2">
                            <label htmlFor="clientId" className="text-sm font-medium text-slate-300">Select Client <span className="text-red-400">*</span></label>
                            <select
                                id="clientId"
                                name="clientId"
                                value={formData.clientId}
                                onChange={handleChange}
                                required
                                className="w-full bg-slate-800/50 border border-white/10 rounded-md px-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all shadow-inner appearance-none"
                            >
                                <option value="" disabled>Select a client...</option>
                                {clients.map(client => (
                                    <option key={client.id} value={client.id}>{client.name}</option>
                                ))}
                            </select>
                            {clients.length === 0 && (
                                <p className="text-xs text-amber-400 mt-1">No clients found. Please add a client first.</p>
                            )}
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <label htmlFor="amount" className="text-sm font-medium text-slate-300">Amount (PKR) <span className="text-red-400">*</span></label>
                                <div className="relative">
                                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm font-medium">Rs</span>
                                    <input
                                        id="amount"
                                        name="amount"
                                        type="number"
                                        step="0.01"
                                        required
                                        value={formData.amount}
                                        onChange={handleChange}
                                        placeholder="0.00"
                                        className="w-full pl-9 bg-slate-800/50 border border-white/10 rounded-md px-4 py-2 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all shadow-inner"
                                    />
                                </div>
                            </div>
                            <div className="space-y-2">
                                <label htmlFor="dueDate" className="text-sm font-medium text-slate-300">Due Date <span className="text-red-400">*</span></label>
                                <input
                                    id="dueDate"
                                    name="dueDate"
                                    type="date"
                                    required
                                    value={formData.dueDate}
                                    onChange={handleChange}
                                    className="w-full bg-slate-800/50 border border-white/10 rounded-md px-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all shadow-inner [color-scheme:dark]"
                                />
                            </div>
                        </div>

                        <div className="space-y-2">
                            <label htmlFor="description" className="text-sm font-medium text-slate-300">Description</label>
                            <textarea
                                id="description"
                                name="description"
                                rows={3}
                                value={formData.description}
                                onChange={handleChange}
                                placeholder="Describe the services or products billed..."
                                className="w-full bg-slate-800/50 border border-white/10 rounded-md px-4 py-2 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 transition-all shadow-inner resize-none"
                            />
                        </div>

                        <div className="flex flex-col sm:flex-row justify-end gap-3 pt-4 border-t border-white/5">
                            <Link href="/dashboard/invoices">
                                <Button type="button" variant="ghost" className="w-full sm:w-auto text-slate-300 hover:text-white">
                                    Cancel
                                </Button>
                            </Link>
                            <Button
                                type="button"
                                variant="secondary"
                                disabled={loading || clients.length === 0}
                                onClick={(e) => handleSubmit(e, false)}
                                className="w-full sm:w-auto"
                            >
                                {loading ? (
                                    <div className="w-4 h-4 border-2 border-slate-500 border-t-white rounded-full animate-spin mr-2" />
                                ) : (
                                    <Save className="w-4 h-4 mr-2" />
                                )}
                                Save Draft
                            </Button>
                            <Button
                                type="button"
                                disabled={loading || clients.length === 0}
                                onClick={(e) => handleSubmit(e, true)}
                                className="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white"
                            >
                                {loading ? (
                                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin mr-2" />
                                ) : (
                                    <Download className="w-4 h-4 mr-2" />
                                )}
                                Generate & Save PDF
                            </Button>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    );
}
